paths:
  source_folder: 'Assets/'
  json_source_file: 'data.json'
  json_destination_file: 'data_mod2.json'
  yaml_destination_file: 'data_ymod2.yaml'
options:
    source: 'file'  # 'file' lub 'object'
    operations: [ 'deserialize_json', 'serialize_json', 'convert_json_to_yaml' ] # mo≈ºliwe operacje [ 'deserialize_json', 'serialize_json', 'convert_json_to_yaml' ]